### ISSUE TITLE
Issue with using imageai with multithreading

### ISSUE THREAD

**Issue by wassimgoodar** [OlafenwaMoses/ImageAI#125]
Hi,
The object detection function works well when used in while loop.
However, when i try to run the same function using threading in python, it does not works.
The error led me to things like session ends,invalid input image path..... but I could not resolve it.
Is it because we cannot use functions of imageai in multithreading in python or is there some more parameters to set.
Errors i got:
 Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1050, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3488, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3567, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("keras_learning_phase:0", shape=(), dtype=bool) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/tensorflow/lib/python3.5/site-packages/imageai/Detection/__init__.py", line 777, in detectCustomObjectsFromImage
    K.learning_phase(): 0
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1053, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("keras_learning_phase:0", shape=(), dtype=bool) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/threadfinal.py", line 53, in read
    objectDetect(imageInProcess)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/singularObjectDetection.py", line 13, in objectDetect
    detections = detector.detectCustomObjectsFromImage(custom_objects=custom, input_image=os.path.join(execution_path,filename), output_image_path=os.path.join(execution_path, "image3new-custom.jpg"), minimum_percentage_probability=30)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/imageai/Detection/__init__.py", line 860, in detectCustomObjectsFromImage
    "Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 

My function
execution_path = os.getcwd()
detector = ObjectDetection()
detector.setModelTypeAsTinyYOLOv3()
detector.setModelPath(os.path.join(execution_path, "yolo-tiny.h5"))
detector.loadModel(detection_speed="flash")
custom = detector.CustomObjects(person=True, dog=True)
def objectDetect(filename):
 humanDetected=False   
 detections = detector.detectCustomObjectsFromImage(custom_objects=custom, input_image=os.path.join(execution_path,filename), output_image_path=os.path.join(execution_path, "image3new-custom.jpg"), minimum_percentage_probability=30)
 for eachObject in detections:
      print(eachObject["name"], " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"])
      print("--------------------------------")
      if(eachObject["name"]=="person"):
          if(humanDetected==False):
             humanDetected=True
             break
          
 print("Finish detecting photo "+ str(humanDetected))  

Thread calls the above function

  q=queue.Queue()
t1=threading.Thread(target=write,args=(q,),daemon=True)
#the write function calls the object detection function

**Comment by wassimgoodar** [comment]
I already try calling the detector.loadModel() in the same thread and even outside the thread yet no positive result was obtained.
I print the path of where the thread was being executed which was same as the path of the main program but yet i got the same error
I did not parse the detector object though,"how to do that"???

**Comment by wassimgoodar** [comment]
here is part of my script
this is my function that the thread t2 calls:
def read():
  print("read "+ os.getcwd())
  execution_path = os.getcwd()
  detector = ObjectDetection()
  detector.setModelTypeAsTinyYOLOv3()
  detector.setModelPath(os.path.join(execution_path, "yolo-tiny.h5"))
  detector.loadModel(detection_speed="flash")
  custom = detector.CustomObjects(person=True, dog=True)
  while True:
    objectDetect("image1.jpg")

And in main:

t2=threading.Thread(target=read,daemon=True)
t2.start()

**Comment by KLiFF2606** [comment]
Hi, is there any news about this issue? I have the same problem.

Here is my thread class:
```
class RetinaNetCaptureThread(Thread):
    detection_speed = "normal"  # possible values: 'fast', 'faster', 'fastest' and 'flash'
    custom_objects = "person"

    def __init__(self, i_capture_handler, srcfile='test3.mp4', src_url=''):
        Thread.__init__(self)

        self.detector = VideoObjectDetection()
        self.detector.setModelTypeAsRetinaNet()
        self.detector.setModelPath(os.path.join(os.getcwd(), "resnet50_coco_best_v2.1.0.h5"))
        self.detector.loadModel(detection_speed=self.detection_speed)

        self.cap = cv2.VideoCapture(srcfile)

        self.keep_tracking = False

    def run(self):
        self.keep_tracking = True
        while self.keep_tracking:
            detections = self.detector.detectCustomObjectsFromVideo(
                custom_objects=self.detector.CustomObjects(person=True),
                camera_input=self.cap,
                return_detected_frame=False,
                output_file_path=os.path.join(os.getcwd(), "tmp_output_video.mp4"),
                save_detected_video=False)
            print('Found detections:', detections)

        print('Capturing thread has stopped.')

    def stop_tracking(self):
        print('Capturing thread was asked to stop.')
        self.keep_tracking = False
````

I get this error:
````
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Dev\AI\Labs\DevoAgencyControl\venven\imageai\Detection\__init__.py", line 1894, in detectCustomObjectsFromVideo
    _, _, detections = model.predict_on_batch(np.expand_dims(frame, axis=0))
  File "C:\Python\Python36\lib\site-packages\keras\engine\training.py", line 1273, in predict_on_batch
    self._make_predict_function()
  File "C:\Python\Python36\lib\site-packages\keras\engine\training.py", line 554, in _make_predict_function
    **kwargs)
  File "C:\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2744, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2546, in __init__
    with tf.control_dependencies(self.outputs):
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 5004, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 4543, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("regression/concat:0", shape=(?, ?, 4), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\Dev\AI\Labs\DevoAgencyControl\venven\CaptureThread.py", line 82, in run
    save_detected_video=False)
  File "E:\Dev\AI\Labs\DevoAgencyControl\venven\imageai\Detection\__init__.py", line 2297, in detectCustomObjectsFromVideo
    "An error occured. It may be that your input video is invalid. Ensure you specified a proper string value for 'output_file_path' is 'save_detected_video' is not False. "
ValueError: An error occured. It may be that your input video is invalid. Ensure you specified a proper string value for 'output_file_path' is 'save_detected_video' is not False. Also ensure your per_frame, per_second, per_minute or video_complete_analysis function is properly configured to receive the right parameters. 
````

The same code works fine when it is inside a while true loop. All my files are in the same folder and I have checked the video and model path are correct.

**Comment by buroa** [comment]
Tried to give them an email to reply ... looks like their email server is even jacked. Opps.

```An error occurred while trying to deliver the mail to the following recipients:
john@deepquest.com
moses@deepquest.com

Technical report:

Reporting-MTA: dsn; a11-78.smtp-out.amazonses.com

Action: failed
Final-Recipient: rfc822; john@deepquest.com
Diagnostic-Code: smtp; 550 5.1.1 <moses@deepquest.com>: Recipient address rejected: User unknown in relay recipient table
Status: 5.1.1

Action: failed
Final-Recipient: rfc822; moses@deepquest.com
Diagnostic-Code: smtp; 550 5.1.1 <moses@deepquest.com>: Recipient address rejected: User unknown in relay recipient table
Status: 5.1.1
```

**Comment by Angus1996** [comment]
When I was using the imageai in my pyqt5 project, I met the same problem.

```
"Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path
```

However I solved that by laoding the model in the function "run()" of my thread. A part of code is like below. Hoping this can be helpful.

```
class run_thread(QThread):
    def __init__(self, parent=None):
        super(run_thread, self).__init__(parent)
        self.isRunning = True
        self.tag = True
        self.cap = cv2.VideoCapture(videoname)
    def run(self):
        execution_path = os.getcwd()
        detector = ObjectDetection()
        detector.setModelTypeAsYOLOv3()
        detector.setModelPath( os.path.join(execution_path , ./yolo.h5"))
        detector.loadModel()
        custom_objects = detector.CustomObjects(bus=True, car=True, truck=True)
        while self.tag:
            if(self.cap.isOpened()==True and self.isRunning == True):
            	ret, frame = self.cap.read()
            if ret:
            	_, contours = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_type="array", input_image=frame, output_type="array", minimum_percentage_probability=30, display_percentage_probability=False, display_object_name=True)
```

**Comment by rola93** [comment]
I think #311 should solve this issue.

Please, upgrade ImageAI (`pip install imageai==2.1.5`) and check if it is solved now.

If this is the case, please close this issue

**Comment by OlafenwaMoses** [comment]
thanks for the comment @rola93 

This issue has been solved in the latest version.

**Comment by skoroneos** [comment]
Greetings.
After spending a couple of days on trying to get imageAI to work with Flask, it was made obvious that the threading issue is not resolved.
To make a long story short if the prediction is executed on a different thread that the model was loaded it fails with the following error

ValueError: Tensor Tensor("predictions/Softmax:0", shape=(?, 56), dtype=float32) is not an element of this graph.

which is the same problem described in this issue and is related to this issue in Keras

I have tried many different solution proposed but nothing worked.
The only way that "worked" is to force Flask not to use threading
i.e
app.run(host='0.0.0.0',threaded = False)

I have not looked into the ImageAI code extensively but for custom image detection using InceptionV3 its 100% sure it does not work with threads.

**Comment by jasondalycan** [comment]
Same issue as @skoroneos.  I'm using ImageAI 2.1.5.

**Comment by PIYUSH9090** [comment]
> This issue has been solved in the latest version.

Not solved in latest version still getting error.  I'm using ImageAI 2.1.5.

**Comment by 1chimaruGin** [comment]
Same issue here.

**Comment by M-Zubair10** [comment]
did the issue solved?
me getting same error when running with thread in selenium
